// import { Outfit } from 'next/font/google'
// import './globals.css'
// import { AppProvider } from '@/context/AppContext'

// const outfit = Outfit({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'],
// })

// export const metadata = {
//   title: 'Blog App',
//   description: 'Generated by create next app',
//   icons: {
//     icon: [
//       { url: '/favicon.ico', sizes: '32x32', type: 'image/x-icon' },
//       { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
//       { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
//     ],
//     shortcut: '/favicon.ico',
//     apple: [
//       { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
//       { url: '/apple-touch-icon-152x152.png', sizes: '152x152', type: 'image/png' },
//       { url: '/apple-touch-icon-144x144.png', sizes: '144x144', type: 'image/png' },
//       { url: '/apple-touch-icon-120x120.png', sizes: '120x120', type: 'image/png' },
//     ],
//     other: [
//       {
//         rel: 'android-chrome-192x192',
//         url: '/android-chrome-192x192.png',
//         sizes: '192x192',
//         type: 'image/png',
//       },
//       {
//         rel: 'android-chrome-512x512', 
//         url: '/android-chrome-512x512.png',
//         sizes: '512x512',
//         type: 'image/png',
//       },
//     ],
//   },
//   manifest: '/site.webmanifest',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={outfit.className}>
//         <AppProvider>
//           {children}
//         </AppProvider>
//       </body>
//     </html>
//   )
// }

import { Outfit } from 'next/font/google'
import './globals.css'
import { AppProvider } from '@/context/AppContext'
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || 'https://quore-it-ai-blogs.vercel.app'),
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon - Simple approach with timestamp for cache busting */}
        <link rel="icon" href={`/images/image.png?t=${Date.now()}`} type="image/png" />
        <link rel="shortcut icon" href={`/images/image.png?t=${Date.now()}`} type="image/png" />
        <link rel="apple-touch-icon" href={`/images/image.png?t=${Date.now()}`} />
        
        {/* Standard favicon sizes */}
      
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        
        {/* Apple Touch Icons for iOS devices */}
        <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
        <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png" />
        
        {/* Android Chrome Icons */}
        <link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png" />
        
        {/* Web App Manifest */}
        <link rel="manifest" href="/site.webmanifest" />
        
        {/* Theme color for mobile browsers */}
        <meta name="theme-color" content="#ffffff" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-config" content="/browserconfig.xml" />
      </head>
      <body className={outfit.className}>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  )
}