import { Outfit } from 'next/font/google'
import './globals.css'
import { AppProvider } from '@/context/AppContext'

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico', 
    apple: '/apple-touch-icon.png',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  )
}